name: build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: harehare/elm-action@v1.0.2
        with:
          elm-version: "0.19.1"
          command: analyse
      - run: elm make src/Main.elm
