name: build
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: harehare/elm-action@v1.0.24
        with:
          elm-version: "0.19.1"
          run: analyse
          working_directory: ./elm1
